### ISSUE TITLE
Bug on session

### ISSUE THREAD

**Issue by r4faelferreir4** [galanblancom/openvidu-flutter#1]
hi @galanblancom 

i was trying to set up a teste and got a problem with the websocket

`E/flutter (11540): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field 'websocket' has not been initialized.
E/flutter (11540): #0      Session.websocket (package:openviduflutter/utils/session.dart)
E/flutter (11540): #1      Session.leaveSession (package:openviduflutter/utils/session.dart:155:5)
E/flutter (11540): #2      CustomWebSocket.onError (package:openviduflutter/utils/custom-websocket.dart:451:13)
E/flutter (11540): #3      CustomWebSocket.connect (package:openviduflutter/utils/custom-websocket.dart:49:7)
E/flutter (11540): #4      _VideocallWidgetState.startWebSocket (package:openviduflutter/screens/videocall.dart:94:17)
E/flutter (11540): #5      _VideocallWidgetState._connect.<anonymous closure>.<anonymous closure> (package:openviduflutter/screens/videocall.dart:127:9)
E/flutter (11540): #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:847:45)
E/flutter (11540): #7      Future._propagateToListeners (dart:async/future_impl.dart:876:13)
E/flutter (11540): #8      Future._completeWithValue (dart:async/future_impl.dart:652:5)
E/flutter (11540): #9      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:722:7)
E/flutter (11540): #10     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (11540): #11     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (11540): `

i can verify that i got a sessionId and token. but when its time to connect to websocket gives this error. Any hints?

and by the way great work so far.

**Comment by galanblancom** [comment]
Hi, can you share what you are trying to do?

**Comment by r4faelferreir4** [comment]
I just did a git clone on the repo and change de params.

 Which version of openvidu you did this?

 Because i needed to change the routes from api-service.dart to match openvidu 2.27.0 API.

**Comment by galanblancom** [comment]
OpenVidu 2.29.0

**Comment by galanblancom** [comment]
Are you testing over a public IP so I can test?

**Comment by r4faelferreir4** [comment]
I just have a server on production and cannot pass the credential.

I am using 2.27.0 openvidu. I managed to fix the socket connection.
but after the connection i'm getting
`SEVERE: 2024-05-20 16:32:46.401797: Server error code 401: Unable to join session teste124. Token {"id":"con_WCJL98ypqo","object":"connection","status":"pending","connectionId":"con_WCJL98ypqo","sessionId":"teste124","createdAt":1716237370056,"type":"WEBRTC","record":true,"role":"PUBLISHER","kurentoOptions":null,"customIceServers":[],"rtspUri":null,"adaptativeBitrate":null,"onlyPlayWithSubscribers":null,"networkCache":null,"serverData":"","token":"wss://ovd.sigeauto.com.br?sessionId=teste124&token=tok_YtgC3tC7Y0OZVBXm","activeAt":null,"location":null,"ip":null,"platform":null,"clientData":null,"publishers":null,"subscribers":null} is not valid. Code: 401`


401 means unauthorized. Maybe i'm missing some configuration

**Comment by r4faelferreir4** [comment]
Found the error.

on the file custom-websocket.dart there is a funciton called joinRoom();

o modified to:
`void joinRoom() {
    final Map<String, dynamic> token = json.decode(session.token);
    final joinRoomParams = {
      JsonConstants.metadata: '{"clientData": "${session.localParticipant?.participantName}"}',
      'secret': '',
      'session': session.id,
      'platform': '${Platform.isAndroid ? "Android" : "iOS"} ${Platform.operatingSystemVersion}',
      'token': token['token'],
      'sdkVersion': '2.27.0',
    };
    idJoinRoom = sendJson(JsonConstants.joinRoomMethod, joinRoomParams);
  }`

need to convert the Session.token to dynamic because its a json. after the the code works

**Comment by galanblancom** [comment]
I think it is because I'm using https://$url/api/sessions/$sessionId/connections to get the token. Let me try with https://$url/api/sessions/$sessionId/connection without the s at the end.

**Comment by galanblancom** [comment]
Without the s I'm getting a 404 :(

**Comment by r4faelferreir4** [comment]
yep. i'm changed to https://$url/api/sessions/$sessionId/connection

and with this gives 2 problems on joinRoom() and getWebSocketAddress();
on both places will need to convert the json.

**Comment by galanblancom** [comment]
I think if someone needs to target another version of OpenVidu (I've only tested for 2.29.0), they'll need to implement a custom ApiService that works for that version.
